// Current elite startlist snapshots for Montréal 2026.
//
// These are factual rider / nation entries, not editorial text. The lists are
// kept outside worlds2026.js so they can be reviewed and replaced without
// touching the race configuration. Current public startlist aggregators are
// used as a completeness cross-check; where a national federation has
// published a conflicting final selection, the federation selection wins.

const squad = (team, names) => names.map((name) => ({ name, team }));

export const MEN_ROAD_STARTLIST = [
  ...squad("Norway", ["Tobias Halland Johannessen", "Tobias Foss", "Embret Svestad-Bårdseng", "Jørgen Nordhagen", "Andreas Leknessund", "Anders Skaarseth"]),
  ...squad("Belgium", ["Remco Evenepoel", "Wout van Aert", "Maxim Van Gils", "Alec Segaert", "Thibau Nys", "Quinten Hermans", "Tiesj Benoot", "Gianni Vermeersch"]),
  ...squad("Mauritius", ["Alexandre Mayer"]),
  ...squad("Italy", ["Alberto Bettiol", "Lorenzo Mark Finn", "Giulio Ciccone", "Mattia Cattaneo", "Giulio Pellizzari", "Davide Piganzoli", "Christian Scaroni", "Matteo Trentin"]),
  ...squad("Portugal", ["Afonso Eulálio", "Ivo Oliveira", "Tiago Antunes", "Nelson Oliveira", "António Morgado"]),
  ...squad("New Zealand", ["Ben Oliver", "Corbin Strong", "Finn Fisher-Black", "George Bennett", "Laurence Pithie"]),
  ...squad("South Africa", ["Byron Munton"]),
  ...squad("Sweden", ["Jakob Söderqvist"]),
  ...squad("Ecuador", ["Richard Carapaz", "Jhonatan Narváez", "Jefferson Alveiro Cepeda", "Jefferson Alexander Cepeda"]),
  ...squad("Ireland", ["Ryan Mullen", "Jamie Meehan", "Darren Rafferty", "Ben Healy"]),
  ...squad("Canada", ["Pier-André Côté", "Nickolas Zukowsky", "Michael Woods", "Michael Leonard", "Hugo Houle", "Derek Gee-West"]),
  ...squad("Poland", ["Michał Kwiatkowski", "Mateusz Gajdulewicz", "Jakub Kaczmarek", "Piotr Pękala"]),
  ...squad("United States", ["Quinn Simmons", "Matteo Jorgenson", "Brandon McNulty", "Neilson Powless", "Sean Quinn", "Artem Shmidt", "Kevin Vermaerke", "Larry Warbasse"]),
  ...squad("Netherlands", ["Mathieu van der Poel", "Mathijs Paasschens", "Menno Huising", "Pascal Eenkhoorn", "Bauke Mollema", "Tim van Dijke", "Bart Lemmen", "Daan Hoole"]),
  ...squad("Spain", ["Juan Ayuso", "Marcel Camprubí", "Enric Mas", "Markel Beloki", "Igor Arrieta", "Carlos Verona", "Raúl García Pierna", "Iván Romeo"]),
  // Danish federation / fresh national-selection reporting lists Skjelmose.
  ...squad("Denmark", ["Mikkel Frølich Honoré", "Kasper Asgreen", "Mikkel Bjerg", "Mads Pedersen", "Andreas Kron", "Michael Valgren", "Søren Kragh Andersen", "Mattias Skjelmose"]),
  // FFC's 11 Sep selection is the authority here: Jegat, not Barré.
  ...squad("France", ["Paul Seixas", "Pavel Sivakov", "Bruno Armirail", "Jordan Labrosse", "Valentin Paret-Peintre", "Nicolas Prodhomme", "Alex Baudin", "Jordan Jegat"]),
  ...squad("Mexico", ["Isaac del Toro", "Eder Frayre", "Edgar Cadena", "Ulises Castillo", "José Antonio Escárcega", "Carlos García"]),
  ...squad("Monaco", ["Victor Langellotti"]),
  ...squad("Brazil", ["Henrique Avancini"]),
  ...squad("Japan", ["Jo Hashikawa"]),
  ...squad("Austria", ["Felix Gall", "Felix Großschartner", "Patrick Konrad"]),
  ...squad("Czech Republic", ["Mathias Vacek", "Jakub Otruba", "Pavel Novák"]),
  ...squad("Colombia", ["Sergio Higuita", "Santiago Buitrago", "Harold Tejada", "Brandon Rivera", "Nairo Quintana", "Wilmar Paredes"]),
  ...squad("Switzerland", ["Fabio Christen", "Jan Christen", "Marc Hirschi", "Mauro Schmid", "Stefan Bissegger", "Stefan Küng"]),
  ...squad("Costa Rica", ["Luis Daniel Oses"]),
  ...squad("Slovenia", ["Tilen Finkšt", "Gal Glivar", "Matevž Govekar", "Luka Mezgec", "Matej Mohorič", "Jan Tratnik", "Primož Roglič", "Jakob Omrzel"]),
  ...squad("Germany", ["Florian Lipowitz", "Marco Brenner", "Georg Zimmermann", "Felix Engelhardt", "Nico Denz", "Maximilian Schachmann"]),
  ...squad("Great Britain", ["Tom Pidcock", "Mark Donovan", "Oscar Onley", "Finlay Pickering", "James Shaw", "Callum Thornley", "Fred Wright", "Adam Yates"]),
  ...squad("Hungary", ["Attila Valter"]),
  ...squad("Algeria", ["Oussama Abdellah Mimouni"]),
  ...squad("Australia", ["Jack Haig", "Jai Hindley", "Michael Matthews", "Ben O'Connor", "Michael Storer", "Luke Tuckwell"]),
  ...squad("Bermuda", ["Kaden Hopkins", "Nicholas Narraway"]),
  ...squad("Belize", ["Derrick Chavarria"]),
  ...squad("Chile", ["Vicente Rojas"]),
  ...squad("China", ["You Li"]),
  ...squad("Cyprus", ["Andreas Miltiadis"]),
  ...squad("Dominica", ["Kohath Baron"]),
  ...squad("Eritrea", ["Amanuel Ghebreigzabhier", "Biniam Girmay", "Merhawi Kudus", "Henok Mulubrhan", "Natnael Tesfatsion"]),
  ...squad("Estonia", ["Madis Mihkels"]),
  ...squad("Guinea-Bissau", ["Gil Landim Gomes"]),
  ...squad("Greece", ["Nikiforos Arvanitou"]),
  ...squad("Guatemala", ["Manuel Rodas", "Juan Mardoqueo Vásquez"]),
  ...squad("Honduras", ["Fredd Matute"]),
  ...squad("Israel", ["Nadav Raisberg"]),
  ...squad("Kazakhstan", ["Anton Kuzmin", "Daniil Marukhin"]),
  ...squad("Saudi Arabia", ["Ali Al Shaikhahmed"]),
  ...squad("Latvia", ["Kristiāns Belohvoščiks", "Emīls Liepiņš", "Mārtiņš Pluto", "Toms Skujiņš"]),
  ...squad("Luxembourg", ["Arno Wallenborn"]),
  ...squad("Mongolia", ["Maral-Erdene Batmunkh"]),
  ...squad("Panama", ["Christofer Jurado Lopez"]),
  ...squad("Romania", ["Iustin-Ioan Văidian"]),
  ...squad("Serbia", ["Mihajlo Stolić"]),
  ...squad("Slovakia", ["Martin Svrček"]),
  ...squad("Thailand", ["Baptiste Poulard"]),
  ...squad("Ukraine", ["Heorhii Antonenko"]),
  ...squad("Uruguay", ["Eric Antonio Fagúndez", "Guillermo Thomas Silva"]),
  ...squad("Uzbekistan", ["Samandar Janikulov"]),
  ...squad("Venezuela", ["Orluis Aular", "Francisco Joel Peñuela"]),
];

export const MEN_ITT_STARTLIST = [
  ...squad("Belgium", ["Remco Evenepoel", "Alec Segaert", "Rune Herregodts"]),
  ...squad("Mauritius", ["Alexandre Mayer"]),
  ...squad("South Africa", ["Byron Munton"]),
  ...squad("Sweden", ["Jakob Söderqvist"]),
  ...squad("Ireland", ["Ryan Mullen"]),
  ...squad("Canada", ["Derek Gee-West", "Michael Leonard"]),
  ...squad("Poland", ["Michał Kwiatkowski"]),
  // Italian federation: Ganna, Sobrero and Cattaneo.
  ...squad("Italy", ["Filippo Ganna", "Matteo Sobrero", "Mattia Cattaneo"]),
  ...squad("Norway", ["Tobias Foss", "Andreas Leknessund"]),
  ...squad("Denmark", ["Mikkel Bjerg", "Kasper Asgreen"]),
  ...squad("Brazil", ["Henrique Avancini"]),
  ...squad("Japan", ["Jo Hashikawa"]),
  ...squad("United States", ["Artem Shmidt", "Brandon McNulty"]),
  ...squad("Czech Republic", ["Mathias Vacek"]),
  ...squad("Colombia", ["Walter Alejandro Vargas", "Brandon Rivera"]),
  ...squad("Spain", ["Pablo Castrillo", "Iván Romeo"]),
  ...squad("Switzerland", ["Stefan Küng", "Stefan Bissegger"]),
  ...squad("Slovenia", ["Jan Tratnik"]),
  ...squad("Netherlands", ["Daan Hoole"]),
  ...squad("Germany", ["Maximilian Walscheid", "Jasha Sütterlin"]),
  // FFC selection: Seixas + Armirail.
  ...squad("France", ["Bruno Armirail", "Paul Seixas"]),
  ...squad("Hungary", ["Barnabás Peák", "János Zsombor Pelikán"]),
  ...squad("Australia", ["Conor Leahy"]),
  ...squad("Bermuda", ["Nicholas Narraway", "Kaden Hopkins"]),
  ...squad("Belize", ["Derrick Chavarria"]),
  ...squad("Cayman Islands", ["Christopher Bodden"]),
  ...squad("China", ["Liu Chenglu", "Cao Houwang"]),
  ...squad("Estonia", ["Madis Mihkels"]),
  ...squad("Great Britain", ["Callum Thornley", "Ethan Hayter"]),
  ...squad("Guinea-Bissau", ["Gil Landim Gomes", "Apolinário Cá"]),
  ...squad("Honduras", ["Fredd Matute"]),
  ...squad("Jordan", ["Majid Abu Harrah"]),
  ...squad("Kazakhstan", ["Anton Kuzmin", "Daniil Marukhin"]),
  ...squad("Luxembourg", ["Arthur Kluckers"]),
  ...squad("Mexico", ["Edgar Cadena", "Isaac del Toro"]),
  ...squad("Mongolia", ["Maral-Erdene Batmunkh"]),
  ...squad("Portugal", ["Ivo Oliveira", "Nelson Oliveira"]),
  ...squad("Rwanda", ["Samuel Niyonkuru", "Shemu Nsengiyumva"]),
  ...squad("Serbia", ["Ognjen Ilić"]),
  ...squad("Ukraine", ["Heorhii Antonenko"]),
  ...squad("Uruguay", ["Eric Antonio Fagúndez"]),
];

export const WOMEN_ROAD_STARTLIST = [
  ...squad("New Zealand", ["Bronwyn MacGregor", "Ella Wyllie", "Henrietta Christie", "Niamh Fisher-Black"]),
  ...squad("Netherlands", ["Demi Vollering", "Femke de Vries", "Karlijn Swinkels", "Puck Pieterse", "Lieke Nooijen", "Riejanne Markus"]),
  ...squad("Norway", ["Katrine Aalerud", "Mie Bjørndal Ottestad", "Sigrid Ytterhus Haugset", "Tiril Jørgensen", "Marte Berg Edseth"]),
  ...squad("Spain", ["Paula Blasi", "Sara Martín", "Mireia Benito", "Usoa Ostolaza", "Mavi García", "Sandra Alonso"]),
  ...squad("Italy", ["Elisa Longo Borghini", "Francesca Barale", "Sara Casasola", "Eleonora Gasparrini", "Erica Magnaldi", "Silvia Persico", "Monica Trinca Colonel"]),
  ...squad("Denmark", ["Cecilie Uttrup Ludwig", "Solbjørk Minke Anderson"]),
  ...squad("Sweden", ["Caroline Andersson", "Julia Borgström"]),
  ...squad("Canada", ["Sarah van Dam", "Olivia Baril", "Nadia Gontova", "Maggie Coles-Lyster", "Magdeleine Vallieres", "Alison Jackson", "Adèle Normand"]),
  ...squad("Japan", ["Karin Abe"]),
  ...squad("United States", ["Lauren Stephens", "Natalie Quinn", "Alexis Magner", "Kristen Faulkner", "Kate Courtney", "Grace Arlandson"]),
  ...squad("Mexico", ["Romina Hinojosa", "Sara Roel", "Andrea Ramírez Fregoso", "Lizbeth Yareli Salazar"]),
  ...squad("Austria", ["Katharina Sadnik", "Carina Schrempf", "Christina Schweinberger"]),
  ...squad("Colombia", ["Paula Andrea Patiño", "Diana Carolina Peñuela", "Laura Daniela Rojas"]),
  ...squad("Belgium", ["Shari Bossuyt", "Lotte Claes", "Lotte Kopecky", "Julie Van de Velde", "Margot Vanpachtenbeke", "Sandrine Tas"]),
  ...squad("Australia", ["Amanda Spratt", "Georgia Baker", "Sarah Gigante", "Lauretta Hanson"]),
  ...squad("Switzerland", ["Ginia Caluori", "Steffi Häberlin", "Noemi Rüegg", "Linda Zanetti", "Jasmin Liechti", "Marlen Reusser"]),
  ...squad("Germany", ["Antonia Niedermaier", "Liane Lippert", "Ricarda Bauernfeind", "Franziska Koch", "Linda Riedmann"]),
  ...squad("Slovenia", ["Nika Bobnar"]),
  // FFC's official road selection has Berthet, not Labous.
  ...squad("France", ["Évita Muzic", "Maeva Squiban", "Léa Curinier", "Célia Géry", "Marie Le Net", "Cédrine Kerbaol", "Juliette Berthet"]),
  ...squad("Hungary", ["Petra Zsankó"]),
  ...squad("Poland", ["Kaja Rysz", "Marta Jaskulska", "Marta Lach", "Katarzyna Niewiadoma", "Dominika Włodarczyk"]),
  ...squad("Algeria", ["Nesrine Houili"]),
  ...squad("Brazil", ["Ana Vitória Magalhães"]),
  ...squad("Bulgaria", ["Gergana Stoyanova"]),
  ...squad("Chile", ["Catalina Anais Soto"]),
  ...squad("China", ["Feng Zhaoqi", "Tang Xin", "Zhu Shimeng"]),
  ...squad("Comoros", ["Najma Najma"]),
  ...squad("Cyprus", ["Antri Christoforou"]),
  ...squad("Eritrea", ["Monalisa Araya"]),
  ...squad("Estonia", ["Ann-Christine Allik", "Janika Lõiv", "Aidi Gerde Tuisk"]),
  ...squad("Finland", ["Ursula Lindén"]),
  ...squad("Great Britain", ["Zoe Backstedt", "Lauren Dickson", "Pfeiffer Georgi", "Anna Henderson", "Flora Perkins", "Alice Towers"]),
  ...squad("Greece", ["Varvara Fasoi", "Argiro Milaki"]),
  ...squad("Guatemala", ["Jasmin Gabriela Soto Lopez"]),
  ...squad("Indonesia", ["Firotika Magh Marenda"]),
  ...squad("Israel", ["Rotem Gafinovitz"]),
  ...squad("Kazakhstan", ["Faina Potapova"]),
  ...squad("Kenya", ["Nancy Akinyi", "Monica Jelimo Kiplagat", "Kendra Masiga"]),
  ...squad("Saudi Arabia", ["Mashael Alhazmi"]),
  ...squad("Luxembourg", ["Nina Berton", "Marie Schreiber"]),
  ...squad("Mauritius", ["Lucie de Marigny-Lagesse", "Kimberley Le Court"]),
  ...squad("Namibia", ["Vera Looser"]),
  ...squad("Panama", ["Wendy Ducreux"]),
  ...squad("Paraguay", ["Agua Marina Espínola"]),
  ...squad("Philippines", ["Mary Joyce Monton"]),
  ...squad("Portugal", ["Daniela Campos", "Raquel Queirós", "Beatriz Roxo"]),
  ...squad("South Africa", ["Lisa Bone", "Tiffany Keep", "Ashleigh Moolman-Pasio", "Hayley Preen"]),
  ...squad("Rwanda", ["Diane Ingabire", "Xaverine Nirere", "Claudette Nyirarukundo"]),
  ...squad("Slovakia", ["Tereza Kurnická"]),
  ...squad("Thailand", ["Pittayapron Seatun"]),
  ...squad("Trinidad and Tobago", ["Teniel Campbell"]),
  ...squad("Ukraine", ["Valeriya Kononenko", "Olha Kulynych"]),
  ...squad("Uzbekistan", ["Madina Kakhkhorova"]),
  ...squad("Venezuela", ["Lilibeth Chacón"]),
  ...squad("Zimbabwe", ["Sky Davidson", "Rongina Ngandu"]),
];

export const WOMEN_ITT_STARTLIST = [
  ...squad("Norway", ["Katrine Aalerud", "Mie Bjørndal Ottestad"]),
  ...squad("Canada", ["Nadia Gontova", "Olivia Baril"]),
  ...squad("Japan", ["Karin Abe"]),
  ...squad("United States", ["Kristen Faulkner", "Taylor Knibb"]),
  ...squad("Austria", ["Christina Schweinberger"]),
  ...squad("Colombia", ["Diana Carolina Peñuela"]),
  ...squad("Belgium", ["Lotte Claes", "Lotte Kopecky"]),
  ...squad("Spain", ["Mireia Benito", "Paula Blasi"]),
  ...squad("Italy", ["Vittoria Guazzini", "Elisa Longo Borghini"]),
  ...squad("Switzerland", ["Jasmin Liechti", "Marlen Reusser"]),
  ...squad("Netherlands", ["Demi Vollering", "Lieke Nooijen"]),
  ...squad("Germany", ["Antonia Niedermaier", "Franziska Koch"]),
  ...squad("Slovenia", ["Nika Bobnar"]),
  // FFC official selection overrides the aggregator: Berthet + Kerbaol.
  ...squad("France", ["Cédrine Kerbaol", "Juliette Berthet"]),
  ...squad("Poland", ["Dominika Włodarczyk"]),
  ...squad("Australia", ["Lauretta Hanson"]),
  ...squad("Bulgaria", ["Gergana Stoyanova"]),
  ...squad("Cayman Islands", ["Alyssa Burgess"]),
  ...squad("China", ["Tang Xin", "Zhu Shimeng"]),
  ...squad("Estonia", ["Ann-Christine Allik", "Janika Lõiv"]),
  ...squad("Finland", ["Anniina Ahtosalo"]),
  ...squad("Great Britain", ["Zoe Backstedt", "Anna Morris"]),
  ...squad("Indonesia", ["Firotika Magh Marenda"]),
  ...squad("Kazakhstan", ["Faina Potapova"]),
  ...squad("Kenya", ["Monica Jelimo Kiplagat", "Kendra Masiga"]),
  ...squad("Saudi Arabia", ["Mashael Alhazmi"]),
  ...squad("Mexico", ["Romina Hinojosa", "Sara Roel"]),
  ...squad("Mauritius", ["Lucie de Marigny-Lagesse"]),
  ...squad("Namibia", ["Vera Looser"]),
  ...squad("New Zealand", ["Henrietta Christie", "Bronwyn MacGregor"]),
  ...squad("South Africa", ["Lucy Young"]),
  ...squad("Rwanda", ["Diane Ingabire", "Xaverine Nirere"]),
  ...squad("Trinidad and Tobago", ["Teniel Campbell"]),
  ...squad("Ukraine", ["Valeriya Kononenko"]),
  ...squad("Zimbabwe", ["Sky Davidson", "Rongina Ngandu"]),
];
